[auth]
type = "none"
userId = "admin"
userName = "Test user"

[summarizer]
model = "default"

[choices]
enabled = true
model = "default"

[[models]]
id = "default"
provider = "anthropic"
model = "claude-haiku-4-5"
displayName = "Default"
supportedMediaTypes = [ "image/png", "image/jpeg", "image/webp", "application/pdf" ]

[[models]]
id = "haiku"
provider = "anthropic"
model = "claude-haiku-4-5"
displayName = "Claude Haiku"
supportedMediaTypes = [ "image/png", "image/jpeg", "image/webp", "application/pdf" ]

[[models]]
id = "sonnet"
provider = "anthropic"
model = "claude-sonnet-4-5"
displayName = "Claude Sonnet"
supportedMediaTypes = [ "image/png", "image/jpeg", "image/webp", "application/pdf" ]

[[personas]]
key = "default"
title = "Default"
model = "default"

[[personas]]
key = "test"
title = "Test model"
model = "test"

[[personas]]
key = "haiku"
title = "Claude Haiku"
model = "haiku"

[[personas]]
key = "pirate"
title = "Pirate"
model = "sonnet"
systemPrompt = "You are a world-class pirate - speak like it!"