# Disable authentication and configure details of our "user"
[auth]
type = "none"
userId = "admin"
userName = "Test user"

# LLM-generated messages are summarized for the tree view with this model
# Use a cheap and fast model here!
[summarizer]
model = "default"

# Enable reply option ("choice") generation
# USe a cheap and fast model here, too!
[choices]
enabled = true
model = "default"

# Configure the models!
[[models]]
id = "default"
provider = "anthropic"
model = "claude-haiku-4-5"
displayName = "Default"
supportedMediaTypes = [ "image/png", "image/jpeg", "image/webp", "application/pdf" ]
features = [ "thinking", "webSearch", "webFetch", "prefill" ]

[[models]]
id = "haiku"
provider = "anthropic"
model = "claude-haiku-4-5"
displayName = "Claude Haiku"
supportedMediaTypes = [ "image/png", "image/jpeg", "image/webp", "application/pdf" ]
features = [ "thinking", "prefill" ]

[[models]]
id = "sonnet"
provider = "anthropic"
model = "claude-sonnet-4-5"
displayName = "Claude Sonnet"
supportedMediaTypes = [ "image/png", "image/jpeg", "image/webp", "application/pdf" ]
features = [ "thinking", "interleavedThinking", "thinkingBudget", "webSearch", "webFetch", "prefill" ]

[[models]]
id = "opus"
provider = "anthropic"
model = "claude-opus-4-5"
displayName = "Claude Opus"
supportedMediaTypes = [ "image/png", "image/jpeg", "image/webp", "application/pdf" ]
features = [ "thinking", "interleavedThinking", "thinkingBudget", "effort", "webSearch", "webFetch", "prefill" ]

[[models]]
id = "gpt-5-mini"
provider = "openai"
model = "gpt-5-mini"
displayName = "GPT-5 mini"
supportedMediaTypes = [ "image/png", "image/jpeg", "image/webp" ]
features = [ "alwaysThinking", "thinkingEffort" ]

[[models]]
id = "gpt-5.2"
provider = "openai"
model = "gpt-5.2"
displayName = "GPT-5.2"
supportedMediaTypes = [ "image/png", "image/jpeg", "image/webp" ]
features = [ "thinking", "thinkingEffort" ]

[[models]]
id = "kimi-k2"
provider = "openaiCompatible"
baseUrl = "https://openrouter.ai/api/v1"
apiKeyEnv = "OPENROUTER_API_KEY"
model = "moonshotai/kimi-k2-thinking"
displayName = "Kimi K2 thinking (OR compat)"
supportedMediaTypes = []
features = [ "alwaysThinking" ]

[[models]]
id = "kimi-k2-or"
provider = "openrouter"
model = "moonshotai/kimi-k2-thinking"
displayName = "Kimi K2 thinking (OR)"
supportedMediaTypes = []
features = [ "alwaysThinking" ]

[[models]]
id = "gemini-or"
provider = "openrouter"
model = "google/gemini-3-flash-preview"
displayName = "Gemini 3 Flash Preview (OR)"
supportedMediaTypes = [ "image/png", "image/jpeg", "image/webp" ]
features = [ "thinking", "thinkingEffort" ]

# Instance's prebuilt personas/presets
# Users can also create their own, these are just the default options!
[[personas]]
key = "default"
title = "Default"
model = "default"
features = [
    { feature = "thinking", value = true },
]

[[personas]]
key = "test"
title = "Test model"
model = "test"
features = []

[[personas]]
key = "haiku"
title = "Claude Haiku"
model = "haiku"
features = []

[[personas]]
key = "pirate"
title = "Pirate"
model = "sonnet"
systemPrompt = "You are a world-class pirate - speak like it!"
features = []

[[personas]]
key = "opus"
title = "Claude Opus"
model = "opus"
features = [
    { feature = "thinking", value = true },
    { feature = "effort", value = "high" },
    { feature = "webSearch", value = true },
    { feature = "webFetch", value = true }
]